[package]
name = "minimal_verifier"
type = "contract"
authors = [""]
compiler_version = ">=0.87.9"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages.git", tag = "v0.87.9", directory = "noir-projects/aztec-nr/aztec" } 