[package]
name = "polkanoir"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"

[lib]
path = "src/lib.rs"

[[bin]]
name = "polkanoir"
path = "src/bin.rs"

[dependencies]
smol = "1.3"
argh = "0.1"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
surf = "2.3"
