[workspace]
members = [
    "lib",
    "tests/depth_8_state_proof",
    "tests/depth_8_storage_proof",
    "tests/one_level",
    "tests/rlp_decode"
]
default-member = "lib"

[package]
name = "noir-trie-proofs"
type = "lib"
authors = [""]
compiler_version = ">=0.87.9"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages.git", tag = "v0.87.9", directory = "noir-projects/aztec-nr/aztec" }
